### ISSUE TITLE
Update Middleman to v4

### ISSUE THREAD

**Issue by roidriscoll** [makersacademy/website#1017]
All of our projects using middleman are quite far behind the current version. From a position of maintainability it's important that we keep up with large changes in frameworks otherwise documentation becomes difficult to follow and bugs are patched in more current releases. According to Nikesh, this upgrade will also give us more options in terms of hosting our blog on the main site.

**Comment by rachelcdavies** [comment]
Some notes might be nice :)

**Comment by roidriscoll** [comment]
The upgrade process for this has been fairly haphazard, mainly due to [this](https://middlemanapp.com/basics/upgrade-v4/) being the best document to reference for the upgrade. I'm finding much is not documented and our approach is much more complex than Thoughtbot seem to expect the average Middleman project to be.

**Comment by roidriscoll** [comment]
Looking better now. Need to go through `config.rb` and see if there is anything I can tidy up, but should be pretty much done. Next task would be to involve the styles via yarn package and get rid of the bower involvement.

**Comment by roidriscoll** [comment]
This is done as far as I can tell. However for the QA phase

**Comment by roidriscoll** [comment]
In order to ensure all of our integrations are working correctly, it would be prudent to deploy a beta version of the site before merging the new changes into the existing site.

**Comment by roidriscoll** [comment]
There's currently an issue with yaml files crashing the build where markdown links are embedded in the text.

**Comment by roidriscoll** [comment]
Managed to find a fix for the markdown link issue - have pushed to the branch. However I have a couple of broken partial links which I need to track down.

**Comment by roidriscoll** [comment]
Fixed incorrect references to some partials. Project now builds successfully. Next step is to deploy to staging and check that all tracking elements remain unaffected.

**Comment by roidriscoll** [comment]
Site deployed to staging, @alexandergimson to take a look tomorrow (25/10)
