### ISSUE TITLE
Swap out 3rd partial on homepage with LR15

### ISSUE THREAD

**Issue by alexkatebailey** [makersacademy/website#1085]
In order to capture people at an earlier stage of the funnel.

Swap link to employers for top partial on LR156 page http://www.makersacademy.com/learn-ruby-in-15/

**Comment by nikeshashar** [comment]
Would this be somewhere for people to enter their email address or a button leading to the LR15 page?

**Comment by alexkatebailey** [comment]
An email capture please. Less clicks!

**Comment by nikeshashar** [comment]
![image](https://user-images.githubusercontent.com/7963753/36726827-fce7216a-1bb2-11e8-9f8d-91dd89205b13.png)
