### ISSUE TITLE
Add logo wall of employers to homepage

### ISSUE THREAD

**Issue by alexkatebailey** [makersacademy/website#1086]
To make it clearer to applicants that we secure devs jobs at top companies.

**Comment by nikeshashar** [comment]
Where would you put this logo wall? It would need to replace a current partial on the site.

**Comment by alexkatebailey** [comment]
Can it go in as part of the top partial, like on the employers homepage?

**Comment by nikeshashar** [comment]
👍 I can mock this up and show you

**Comment by nikeshashar** [comment]
- [ ] Copy the logos_grid from employers.ma.com
- [ ] Create logos_grid as a partial
- [ ] Test on staging
