### ISSUE TITLE
Career Support Page

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#1105]
We need a full overhaul on this page. @alexkatebailey to tell me what segments to put on + include email capture somewhere.

**Comment by alexkatebailey** [comment]
This one's ready to go! More info about to drop in the engineering channel

**Comment by nikeshashar** [comment]
Ticket priority #1: Redo Career Support Page 

H4: CHANGE YOUR CAREER
H2: BECOME A FIRST-RATE JUNIOR DEVELOPER
P: With the largest Careers Team of any UK bootcamp, we’ll guarantee you a job within 6 months or your money back.
H4: We’ve trained 1,400+ developers who have started amazing careers at 300+ companies.

Background photo: Careers Team (Contact Baz for high res image)
Logo wall: same as homepage

Next partial: header + 3 column

H2: THE FASTEST ROUTE INTO THE TECH INDUSTRY
P: Upskill and transition into a new career in 16 weeks.

H3: £30-35k
P: Because of their accelerated career trajectory, our brilliant developers typically start on an average of £32k and earn up to £40k a year later.

H3: x% hired with 2 weeks
P: With two in-house Careers Coaches on-site, you’ll get 1:1 career support coaching to help you identify the best role for you.

H3: 300+ companies
P: Our Careers Team have relationships with some of the most progressive organisations in the UK on the cutting-edge of digital innovation.

Next partial:

H2: SECURE YOUR DREAM JOB AT A COMPANY OF YOUR CHOICE
P: We run Careers Fairs in partnership with 15 different companies every month at Makers. With 20-40 roles on offer there’s more jobs on offer than people!

Careers Fair video: https://www.youtube.com/watch?v=SrKt9HYS92o

Next partial:
H2: BOOK A CAMPUS TOUR
P: Based in the heart of Shoreditch We run a daily campus tour at 11.00 every Thursday and Friday.

Eventbrite embed // Button link to Eventbrite

Revolving quote partial:

“Makers enabled me to change my life. I wanted to do something which I was passionate about, so I made the scary decision to change careers and pursue software development. I now work at one of the hottest tech startups and work with some of the most brilliant and talented people - building amazing solutions, learning at an accelerated pace and I love I what do. I never thought I would actually say that I look forward to going work.”

Costas Kiteou
Software Engineer

“If you love to learn, interested in coding and challenge motivates you and want to change careers then Makers Academy is definitely the place to go. Amazing vibe, knowledgeable and patient coaches and the curriculum is the absolute best.

Laszlo Bogacsi, Software Developer

“Makers Academy is Europe's leading web development bootcamp for a reason. It's highly selective because the course will take you from next-to-zero knowledge to a skilled professional in a matter of weeks.”

Chris Harrop, Software Engineer
