### ISSUE TITLE
Dania Mah - shortened

### ISSUE THREAD

**Issue by adeleemily** [makersacademy/website#1136]
(I've put the rest into blog post)

Full name
thatdania (Dania Mah) 

Github
https://github.com/thatdania

What Cohort were you and when did you graduate?
I was in the October '17 cohort and graduated on January 19th, 2018.

What were you doing before joining MA?
I had just finished my Graphic Design and Communication Degree, doing GIFS at Central Saint Martins in July 2017. 

How did you come across MA and what made you decide to apply?
A friend of mine whom I went to boarding school in Australia did the course during one of her summers and she recommended me to do the course as it was "life-changing". 

What did you find difficult?
This is going to sound strange but the hardest hurdles are allowing the changes that will happen to you over the course, whether it'd be in code, in yourself or the life around you. It's not easy to change the way you think, the way you see things, to focus on the progress of the present day rather thinking ahead and to realize that you didn't know yourself as well as you thought. 

How has your life changed since learning to code? 
I'm unafraid to chase my dreams and go through the struggles. No matter how bad the situation is, the experience at Makers teaches you that things will always work out somehow. 

What advice would you give to people thinking of changing career?
You are never too old and never too late to start, especially if your passion is in tech. 

What would you say to people who say £8000 is expensive for an online course?
I really think you would get your full money's worth by going onsite and I say that because of the experience you'll have with your cohort. 

What was your biggest fear before joining MA and how do you feel about it now?
Learning logic as I didn't do so well in Math. However, you'd be surprised how coding is actually a creative process. I've learned a lot about erasing assumptions and never to underestimate yourself whilst overcoming these fears. 

Sum up your Makers Academy experience...
I've come out feeling so much more balanced. I feel so much more sure of myself but also feel more prepared for the next steps as I have the tools to keep growing. It was a really personalised and explorative experience when it came to learning code at Makers, and that's really how one should be learning code.

**Comment by nikeshashar** [comment]
Updated

**Comment by nikeshashar** [comment]
Pushed to branch #1128. Awaiting images from marketing team.
