### ISSUE TITLE
Add Dana, Spike and Steve to the website

### ISSUE THREAD

**Issue by sjmog** [makersacademy/website#143]
The only ones left. Photos, cut-out, and bios required.

**Comment by nikeshashar** [comment]
- [ ] Dana
- [ ] Stephen
- [ ] Spike

**Comment by nikeshashar** [comment]
@sjmog - Dana and Stephen on the site. From memory Spike didn't want  to be on the site so we agreed to leave him off. Closing this ticket

**Comment by spike01** [comment]
I'm happy to be added to the site in the next batch.

**Comment by pitchinvasion** [comment]
I'm pushing for a photographer to take pro pics of us, we can update the team then

**Comment by nikeshashar** [comment]
We need a new team photo - half of the people in that photo don't work for MA anymore.
