### ISSUE TITLE
Top of graduates page should have a 'Looking to Hire Graduates?' button

### ISSUE THREAD

**Issue by sjmog** [makersacademy/website#172]
This should be in place of email capture, and go to the 'employers' page.

**Comment by nikeshashar** [comment]
We have the employers page to "hire" grads from. Do we want two CTA's taken away from people applying to the course?

**Comment by pitchinvasion** [comment]
Worth an A/B test? Do we have somewhere where we plan A/B tests? Maybe on marketing waffle?

**Comment by nikeshashar** [comment]
We've kind of decided that we don't have enough data for A/B tests (IMO). But Arfah is the person to go to for these

**Comment by sjmog** [comment]
Echoing @nikeshashar - we have to think *very* carefully before adding extra calls to action.

And the nav is completely out of bounds :p.

But seriously, we've worked hard to get this UX working so let's keep it that way. Every extra button, helpful for one in ten visitors, is extra effort for nine out of ten.

**Comment by nikeshashar** [comment]
I'm going to close this for now and we can reopen after / when Will has done his landing pages.

**Comment by pitchinvasion** [comment]
Yeah that's true although it's always worth seeing if we can improve it and we all agree getting employers is important in the new year. 

Also that's just not true about A/B tests it's maybe hard on say the apply form as so few people submit applications but it's totally valid on say the landing pages which get tens of thousands of hits a month

**Comment by nikeshashar** [comment]
I was only echoing what you told me @pitchinvasion - our A/B tests don't generate any useful information for us.
