### ISSUE TITLE
Github Link on our Website

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#236]
We should have our Github link on the site

**Comment by spike01** [comment]
Once we've cleaned our Github

**Comment by nikeshashar** [comment]
Are we any closer to getting this cleaned up?

**Comment by spike01** [comment]
Yeah, we're actually in pretty good shape at the moment

**Comment by spike01** [comment]
Might be worth the whole team doing a once over of all our code, both for this and because it's a good idea in general, as well as taking some time to put work into the style guide

**Comment by pitchinvasion** [comment]
Yeah it's looking pretty good, and agreed as long as the once over is more about reading and seeing what's there and maybe doing small changes if need be - I feel like I've been particularly guilty recently of doing too much refactoring and focusing not enough on product, personally I'd like us to spend the next few months more focused on building stuff
