### ISSUE TITLE
Cookie information to Pipedrive

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#243]
Can we extract the date the cookie was placed for a user into Pipedrive so we can see how long it took someone to make a decision

**Comment by nikeshashar** [comment]
@pitchinvasion = is this possible to see on Customer.io?

**Comment by pitchinvasion** [comment]
Customer.io has a created date which is the first time they were identified (either when they signed up for the newsletter or submitted an application) but we can't get the first time they hit the website - Mixpanel has that though, we could add a link to their mixpanel data via pipedrive but I'm not sure of the value in that

**Comment by pitchinvasion** [comment]
What would be the need for it?

**Comment by nikeshashar** [comment]
Well I want to get an idea of how long it takes from someone first seeing us anywhere and then deciding to join. We don't have that data anywhere that I can see easily.

**Comment by pitchinvasion** [comment]
Easiest way of doing that is me and Stefan to finish up our ticket which is basically getting all of our data into a database (!) via segment and then we can build a page with custom reports. Mix panel can't handle some of the queries we're looking for.

**Comment by nikeshashar** [comment]
Okay. Can you let me know when you do that so I can tell what reports would be useful to me.
