### ISSUE TITLE
Further SEO upgrades

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#247]
Results from SEO Checker : 

- [ ] 16 images tags are missing ALT attributes
- [ ] 51 inline CSS styles
- [ ] Add a print style sheet
- [ ] CSS Sprites to lower HTTP requests
- [ ] Image map for Curriculum
- [ ] Minify Hotjar JS file

Current score 75 / 100 on 02 July 2015 (seositecheckup.com). More tests to follow

**Comment by roidriscoll** [comment]
Image map should be separate ticket?

**Comment by nikeshashar** [comment]
I'll update the SEO again once we move the site out of Beta.
