### ISSUE TITLE
Reduce textual content on the website

### ISSUE THREAD

**Issue by sjmog** [makersacademy/website#279]
Text content on the website is too 'in-your-face'. We need to design some clear interactions for how we deal with excessive content (for example, the fixed menu for FAQs).

**Comment by sjmog** [comment]
This will need to be broken into tickets addressing text chunks by 'type' of text (3 options, Quick sale, Longer info, etc).

**Comment by sjmog** [comment]
@roidriscoll points out that at the moment we have only one component for all 'types' of text, which is `.article`

**Comment by rubenkostucki** [comment]
This is really cool for icons btw - https://thenounproject.com/

**Comment by sjmog** [comment]
Absolutely. We'll need a custom set, something like Noun Project or Fontastic.me has this option (as well as custom SVG icons)
