### ISSUE TITLE
Long feedback from my cousin on the website

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/website#321]
initial text

Makers Academy is Europe's leading Web Developer bootcamp. With our help, you'll learn the principles of software craftsmanship and we'll also help you get your first job

I would change sentence two so that you don't use the word help twice.

Either change the second help to "assist"

or the first one to: with our expertise, with our experienced professors (maybe too formal)

Get what I mean?

Explaining which languages students will learn and their use is super cool

"Located at the heart of Silicon Roundabout with a big work space" - come up with something nicer than "big work space"

It's a unique office, tell me how!

this is a small nitpicky thing, but at the top of the website, I would change the order of the tabs to what people (and by people, i mean I) would be most likely to click on:

About Us

Curriculum

Partners

Graduates

Or maybe Graduates after Curriculum

From Left to right

I love that that tab hides when you scroll down

On the about us tab:

Makers Academy is a fully immersive, full-time computer programming course in London, designed to turn people with no knowledge of web development into job-ready junior developers in just 12 weeks. We’re Europe’s #1 Developer Bootcamp, running new classes of 25 students every 6 weeks, and we’re based in the heart of London’s Tech City.

the first sentence is pretty wordy, get rid of the "in London" as you say it at the end

Or you could just start the sentence with

Based in the heart of London's tech city, Maker's Academy is... (although I can see the appeal of starting the sentence with Maker's)

"Dana, our Chief Joy Officer - a certified yoga instructor who runs daily yoga and meditation classes and is here to look after your well being"

The second half of this sentence is kinda awkward. Also, well-being is usually hyphenated.

Our story:

"Makers Academy has now been going for over 2 years"

Change the going to educating or innovating, or something along those lines

the about us page is really long/requires a lot of scrolling - especially to get to the FAQ

i would either put a sub-tab under the About Us at the top of the page to let people jump directly to the FAQ

or Put the FAQ on another tab

yeah I would deff organize the about us page

for example

there is only one button to get to the our team thing

I know you hate hierarchy, but maybe organize the "our team" as a grid rather than requiring the user to keep clicking an arrow to see all teamembers. or maybe organize it by teachers/admin (although everyone can be a teacher!) -- but people like to know who is teaching them

There are very few links to the ronin online course (I know you guys aren't super keen on having people do it), but the links should be easier to find (or not....)

ooooh you hadn't told me about the monetization aspect of the recruiting

that is really cool!!

there is no tab on top specifically for employers

I get that you can get to it in the partners tab

but maybe have a link somewhere titled: for employers (unless oyu think it'd be distracting)

"Our fee is also greater than some other sources of recruitment, because working with Makers Academy is much more than simply getting a list of keyword-matched CVs." 

I'd be interested in hearing the logic behind the beginning of this sentence. On the one hand, I always thought that you should never tell a buyer that you're more expensive than the other options. On the other, I feel like there is a good reason behind saying it: maybe as reassurance that the person is paying for quality/you are aware of the burden of charging more (and how it pushes you to work harder --- which you say)

**Comment by Arfah** [comment]
Fair points but a lot of the points are very minor.

**Comment by rubenkostucki** [comment]
very minor == easy wins so worth doing or not?

On Thu, Aug 6, 2015 at 1:17 PM Arfah <notifications@github.com> wrote:

> Fair points but a lot of the points are very minor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/site-mvp/issues/321#issuecomment-128345251>
> .
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>

**Comment by rubenkostucki** [comment]
I have a feeling that with feedback like these, fine combed and detailed +
quite quick to change if we think it makes sense, we should do it. That's
the value of receiving feedback, especially on a freshly launched website.

My 2p, your call.

On Fri, Aug 7, 2015 at 12:03 PM Ruben Kostucki <ruben@makersacademy.com>
wrote:

> very minor == easy wins so worth doing or not?
>
> On Thu, Aug 6, 2015 at 1:17 PM Arfah <notifications@github.com> wrote:
>
>> Fair points but a lot of the points are very minor.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/makersacademy/site-mvp/issues/321#issuecomment-128345251>
>> .
>>
> --
> *___________________________*
>
> *Ruben Kostucki, **COO*
>
> *+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
> <http://www.makersacademy.com/>*
>
> Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
> <http://linkedin.com/in/rubenkostucki>
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>

**Comment by Arfah** [comment]
Not saying i won't do it just at the moment my priority is getting all my
landing pages launched and campaigns then i can start going over this
stuff. Otherwise i just get distracted and don't get anything done.

**Comment by Arfah** [comment]
Also reading it again i don't agree with everything mentioned. There is a
reason why its a partners page and not employers in the heading. Samm was
pretty keen to keep the nav simple otherwise we gnna end up with tbe same
old messy nav bar from the old site.

**Comment by rubenkostucki** [comment]
Absolutely: feedback has to be taken with a pinch of salt pepper and paprika :)




But some of it makes sense, for example the use of "help" two times at the beginning 



—
