### ISSUE TITLE
Article text looks wrong

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#323]
When you make the width of the site somewhere around 600px (basically as wide as possible before it goes to the desktop breakpoint) it looks wrong, see screenshot

**Comment by pitchinvasion** [comment]
![image](https://cloud.githubusercontent.com/assets/208986/9114403/9508a750-3c51-11e5-9f77-a8ddd8e0cf0e.png)

**Comment by spike01** [comment]
It's also just a bit narrow in general across the site at desktop widths

**Comment by pitchinvasion** [comment]
Blocked by #207

**Comment by tansaku** [comment]
@pitchinvasion #207 is now merged - so is this unblocked now?
