### ISSUE TITLE
Ronin Specific Curriculum Info

### ISSUE THREAD

**Issue by jordanpoulton** [makersacademy/website#334]
https://files.slack.com/files-pri/T028WMLPG-F08SGEBRU/screen_shot_2015-08-10_at_16.38.14.png

--
TEXT:

We need to show the Ronin Specific Educational information:

Full Time – Like the students who attend our real-time, face-to-face school, you'll be working full time, because this is by far the best way to learn to code. You'll be expected to be at your desk from at least 9am-6pm, Monday-Friday, for the duration of the 12 week course, spending the day pairing with your partner and attending daily standups at 9:30am and 2:30pm. We also have a 4 week Pre-Course, which can be done part-time. (At least 20 hours per week, preferably much more.)

Project-based learning – While the first half of the course focuses on the fundamentals of web development, the second half focuses heavily on students creating real-life projects for their portfolio. You'll leave the course with at least three completed projects - a great asset to show a potential employer. You'll also get to work on team projects, and we'll even offer you experience delivering work for a client, mimicking the work you'll be doing when you start your life as a developer.

More than just syntax – Makers Academy is at the head of a global movement in the software industry. Gone are the days when engineers were locked in a room and told to thoughtlessly bash out thousands of lines of ugly code. Nowadays, the best engineers are artisans, writing Test-Driven, beautiful, readable code. It's next-to-impossible to teach yourself in this way; those who achieve such heights spend years honing their technique. Our students learn to code this way from the day 1, which is why so many awesome companies queue round the block to hire them.

Pair Programming – There is a tired stereotype of the introverted developer, locked in his room with the curtains closed, surrounded by cats and stale pizza. That stereotype is, thankfully, confined to the history books. Nowadays the best developers are also great communicators, and there is no better way to do this than to pair programme every day, constantly discussing and debating your code. At Makers, pairing is right at the heart of our model, and you'll be a pro by the time you graduate

**Comment by ptolemybarnes** [comment]
Hey @jordanpoulton is this still wanted?
