### ISSUE TITLE
Add/change graduates on site

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#367]
- [ ] add back Denise
- [ ] change the person on front page to keep things fresh?

@arfah any thoughts on who should be our next cover star?

**Comment by Arfah** [comment]
I'll take this ticket. I'm in the process of putting up new case studies,  George, Zeeshan, Chris Ward, Sammy... Sammy and George have the white background pic so i'll prob maybe go for Sammy as he is recent
