### ISSUE TITLE
New UX flow to match the new nav bar

### ISSUE THREAD

**Issue by sjmog** [makersacademy/website#374]
Front page 'Our Hiring Partners' section goes to partners, which is now orphaned. It needs to go to 'Employers' instead.

Link wording needs to be updated to reflect this.

**Comment by pitchinvasion** [comment]
Updated now we need to do a new flow where the employers page at the very least has a link to an apply button

**Comment by pitchinvasion** [comment]
This is now unclear, I'll discuss with @isoworg and ticket this up properly for next sprint

**Comment by sjmog** [comment]
What about the PR attached to this? I think it covers all the bases @pitchinvasion

**Comment by pitchinvasion** [comment]
OK cool I'll look over it and do it
