### ISSUE TITLE
A/B Test - Copy - Women

### ISSUE THREAD

**Issue by jordanpoulton** [makersacademy/website#380]
At the bottom of the page, we have the 'big apply button'. I would like to a/b test adding an asterisk underneath the button that says:

"Message to all Women! Our experiences over the past few years have confirmed existing academic research on gender. Specifically, that men are likely to over-estimate their talents and apply early. Women tend to under-estimate themselves and delay. If you're reading this and wondering whether to apply, the answer is yes. Apply. Now. Not once you’ve studied a bit more. Not once you're a better programmer or your application is totally perfect. TODAY. Do not under-estimate your experiences and talents. The tech industry needs more women like you.”

**Comment by spike01** [comment]
- we already have the text inviting people to check out Ronin: do we keep that too and just tack this on below?
- are we allowed to use Hackership's copy word for word?

**Comment by pitchinvasion** [comment]
also what are we testing here? As we don't capture gender if you're testing to see if more women sign up, we'd just be seeing if applications go up generally

**Comment by spike01** [comment]
@jordanpoulton: any input?

**Comment by jordanpoulton** [comment]
Sorry - only just saw this. I say tack it on to the bottom, and we'll see anecdotally if we get more applicants. Probably not worth A/B testing, as our samples are too small and as you say, we don't track gender at the moment. 

We sort of know it will be a nice thing to add, so shall we just add it under the Ronin text?

Slightly tweaked text @spike01

"Message to all Women! Our experiences over the past few years have confirmed [academic research on gender](https://hbr.org/2014/08/why-women-dont-apply-for-jobs-unless-theyre-100-qualified/) . Specifically, that men tend to over-estimate their talents and apply early, while women tend to under-estimate themselves and delay. If you're reading this and wondering whether to apply, the answer is yes. Apply. Now. Not once you’ve studied a bit more. Not once you're a better programmer or your application is totally perfect. TODAY. Do not under-estimate your experience and talents. The tech industry needs more women like you.”

**Comment by pitchinvasion** [comment]
@jordanpoulton I think we still need to discuss this, with the Ronin apply text under the main text there's not much room, and we need to decide if we're going to prioritise the Ronin text as per the new marketing strategy

**Comment by tansaku** [comment]
@pitchinvasion - did you have a chance to have a follow up discussion with @jordanpoulton about this?

**Comment by pitchinvasion** [comment]
Yeah we agreed there's too much info I'll move it back to ideas
