### ISSUE TITLE
Fix sass warnings

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#395]
We get these every time we run tests

DEPRECATION WARNING on line 11 of /Users/leo/Code/applications/bower_components/makers_styles/source/sass/_vertical_tabs.scss:
Assigning to global variable "$medium-screen" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$medium-screen: em(640) !global !default" instead.
Note that this will be incompatible with Sass 3.2.

DEPRECATION WARNING on line 12 of /Users/leo/Code/applications/bower_components/makers_styles/source/sass/_vertical_tabs.scss:
Assigning to global variable "$base-font-color" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$base-font-color: $dark-gray !global !default" instead.
Note that this will be incompatible with Sass 3.2.

**Comment by spike01** [comment]
I'm not getting this when I run tests, either here or on applications (which is where you stack trace is from) - which repo should this ticket be open on?

**Comment by pitchinvasion** [comment]
Hmm lets pair on this today might be my computer

**Comment by tansaku** [comment]
@pitchinvasion @spike01 did you guys get to pair on this?

**Comment by spike01** [comment]
No, which is why it's still in the backlog

**Comment by tansaku** [comment]
@pitchinvasion @spike01 - get this on applications and not on website:

DEPRECATION WARNING on line 4 of /Users/tansaku/Documents/Github/MakersAcademy/applications/bower_components/makers_styles/source/sass/_tabs.scss:
Assigning to global variable "$base-border-color" by default is deprecated.
In future versions of Sass, this will create a new local variable.
If you want to assign to the global variable, use "$base-border-color: gainsboro !global !default" instead.
Note that this will be incompatible with Sass 3.2.
