### ISSUE TITLE
Add Dana and Ollie to website

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#397]
https://files.slack.com/files-pri/T028WMLPG-F0BGRA6UC/image_ready.jpg

1 Comment
Dana is our Chief Joy Officer. She facilitates the well being of the students and staff. Everything from personal/group chats and advice to daily meditation. She is also our in-house Yoga teacher (RYT). Dana loves music and fun!

**Comment by pitchinvasion** [comment]
Waiting on Dana's pic once that's done we can deploy

**Comment by tansaku** [comment]
@pitchinvasion - did we get dana's pic?
