### ISSUE TITLE
Curriculum content on landing page - improve

### ISSUE THREAD

**Issue by jordanpoulton** [makersacademy/website#399]
On www.makersacademy.com we have a slider that explains what students will learn. It only covers 4 things: Ruby, HTML, Javascript and Git. It should cover a lot more. 

The content can be taken from the 'what you'll learn' section from http://www.makersacademy.com/curriculum/

**Comment by nikeshashar** [comment]
Do we have the logo's made?

**Comment by tansaku** [comment]
@nikeshashar @jordanpoulton any movement on this?

**Comment by tansaku** [comment]
@nikesh @jordanpoulton @roidriscoll have found some logos here: https://github.com/makersacademy/makers-assets/tree/gh-pages/images/technologies @roidriscoll if you can find the original photoshop file for this much appreciated
