### ISSUE TITLE
***important*** - CHANGE RONIN TASTER DAY LINK

### ISSUE THREAD

**Issue by jordanpoulton** [makersacademy/website#404]
The JS popup that links you in to the Ronin Taster Day is now obsolete. Please swap for this:

https://www.eventbrite.co.uk/e/be-a-ronin-student-for-the-day-tickets-18496692104?discount=RONIN_STUDENT

**Comment by sjmog** [comment]
Which site is this on @jordanpoulton?

**Comment by sjmog** [comment]
Oh got it

**Comment by sjmog** [comment]
Done @jordanpoulton
