### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#407]
Add FT logo

**Comment by nikeshashar** [comment]
@rubenkostucki - can you source this please?

**Comment by rubenkostucki** [comment]
Can you please ask Will, I'm not in touch with them. Or use
https://www.google.fr/search?q=financial+times+logo&espv=2&biw=1422&bih=753&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMI6N6j6aC7yAIVyQMaCh21Kw17#tbm=isch&q=financial+times+logo+transparent
or
in vector format?



On Sat, Oct 10, 2015 at 4:16 PM Nikesh Ashar <notifications@github.com>
wrote:

> @rubenkostucki <https://github.com/rubenkostucki> - can you source this
> please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/website/issues/407#issuecomment-147093093>
> .
>
-- 
*___________________________*

*Ruben Kostucki, **COO*

*+44 774 829 9962 <%2B44%20774%20829%209962> | **www.makersacademy.com
<http://www.makersacademy.com/>*

Twitter <http://www.twitter.com/rubenkostucki>    |    Linkedin
<http://linkedin.com/in/rubenkostucki>
