### ISSUE TITLE
Idea: Easter Egg in the Code.

### ISSUE THREAD

**Issue by Adzz** [makersacademy/website#409]
As a prospective student, I think it would be cool to have an easter egg in the code, so that others think you're awesome too.

I think it could be a fun idea to include an easter egg in the code. Something like this:

<img width="1440" alt="1" src="https://cloud.githubusercontent.com/assets/8428277/10373657/1e796e1a-6def-11e5-94f0-32bc0cfecfb9.png">

<img width="1440" alt="2" src="https://cloud.githubusercontent.com/assets/8428277/10373686/4ef39c46-6def-11e5-82fc-eae0d1e5433e.png">

<img width="1440" alt="3" src="https://cloud.githubusercontent.com/assets/8428277/10373696/5cc75876-6def-11e5-8317-9ba169fc5c7d.png">

**Comment by pitchinvasion** [comment]
Great idea thanks for the suggestion @Adzz we've been wanting to do something like this for a while and we'll have a go at adding something when we get a chance :)
