### ISSUE TITLE
womens-landing-page

### ISSUE THREAD

**Issue by Arfah** [makersacademy/website#417]

**Comment by tansaku** [comment]
any more details on this @arfah?

**Comment by spike01** [comment]
This is deployed I think? http://www.makersacademy.com/women

**Comment by spike01** [comment]
(I think the PR didn't get linked)

**Comment by tansaku** [comment]
@spike01 so move to done column?

**Comment by spike01** [comment]
I'll double check with Arfah if anything more needs to be done

**Comment by Arfah** [comment]
Nope it's done. I think i did the closes # wrong.

**Comment by tansaku** [comment]
I'll move it over :-)
