### ISSUE TITLE
remove "head of education" term from website

### ISSUE THREAD

**Issue by tansaku** [makersacademy/website#429]
copy changes to website including removing role, and reference to role in student contract etc.

**Comment by nikeshashar** [comment]
@tansaku - what role are you assigning?

**Comment by pitchinvasion** [comment]
I'm imagining it's coachineer

**Comment by spike01** [comment]
I don't mind the term internally, but how do we feel about being called "Coach/Engineer" or even "Engineer/Coach" externally? I have had people ask "wtf is a coachineer" before

**Comment by nikeshashar** [comment]
+1

**Comment by nikeshashar** [comment]
changing to coachineer for now. If we want to change everyone's title that can be another ticket
