### ISSUE TITLE
Nav bar text

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#430]
Third option says online but when you click on it, goes to about-us

**Comment by nikeshashar** [comment]
<img width="1440" alt="screen shot 2015-10-21 at 15 46 21" src="https://cloud.githubusercontent.com/assets/7963753/10640094/1dcdf60e-780b-11e5-9751-ebb19fda6d31.png">

**Comment by nikeshashar** [comment]
Online isn't up there anymore. Can we close this ticket?

**Comment by pitchinvasion** [comment]
yes
