### ISSUE TITLE
Switch from Mixpanel to Customer.io/Segment for email sign ups

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#434]

**Comment by nikeshashar** [comment]
@pitchinvasion - can I have a look at what the system does in terms of filtering segments for new emails going out before we decide?

**Comment by tansaku** [comment]
@pitchinvasion - can you write a short summary of why this switch is needed? thanks

**Comment by pitchinvasion** [comment]
better segmenting for marketing - basically mixpanel doesn't work very well with emails/drip campaigns so we're shutting mailchimp down and merging things into customer io. speak to @Arfah or @nikeshashar if you want more detail as it was a marketing decision

**Comment by tansaku** [comment]
cool thanks @pitchinvasion - appreciate the summary

**Comment by pitchinvasion** [comment]
- [ ] replace mailchimp.jquery with small jquery for email capture
- [ ] allow to capture data-segments property and upload
- [ ] install to bower so that we can then use this to transfer everything else across

**Comment by tansaku** [comment]
hi @pitchinvasion - any update on this - all going well?

**Comment by pitchinvasion** [comment]
working on it now

**Comment by tansaku** [comment]
pull request not linking for some reason: https://github.com/makersacademy/website/pull/443
