### ISSUE TITLE
Switch to Segment

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#439]
- [ ] Replace all newsletter sign-ups with the new segment sign-up box, including adding in relevant segments
- [ ] Replace all calls to mixpanel with calls to segment

**Comment by tansaku** [comment]
@pitchinvasion - hope this proceeds well - would love more insights into the tech when the chance arises

**Comment by tansaku** [comment]
not linking to https://github.com/makersacademy/website/pull/446 for some reason
