### ISSUE TITLE
Update FAQ regarding interview technique

### ISSUE THREAD

**Issue by jordanpoulton** [makersacademy/website#444]
Current text on FAQ page: ""In truth, there isn't a huge amount you can do to improve your chances at the interview stage. It's designed to find people who have natural intelligence, bags of drive and clear passion for learning to code. We're not testing what you do or don't know"

TO:

"In truth, there isn't a huge amount you can do to improve your chances at the interview stage - other than following the instructions we give you and studying the materials that we recommend. It's designed to find people who have natural intelligence, bags of drive and clear passion for learning to code. We're not testing whether you've memorised syntax - we're testing whether you can follow instructions and have the passion to learn some basic code without our support."

**Comment by silvabox** [comment]
@jordan, can we change 'natural intelligence' to 'natural reasoning'?  'Natural intelligence' seems a bit tautological.

**Comment by tansaku** [comment]
@jordanpoulton - pull request?
