### ISSUE TITLE
Extract index/landing page to partials

### ISSUE THREAD

**Issue by spike01** [makersacademy/website#460]
The following 5 pages have a lot of duplicated content, which would suggest that they should be extracted to partials (and this would help Arfah build landing pages faster in future)

- index
- career-changers
- education-leavers
- entrepreneurs
- women

**Comment by sjmog** [comment]
Which partials would you suggest here @spike01 ?

**Comment by spike01** [comment]
From index.haml
* Curriculum
* Meet our grads
* Meet our hiring partners 

Then, the landing pages all follow a very similar structure - splash statement, why should you consider a career in web development, this could be you. Maybe a switch to something config based (makes checking copy and making more pages way easier). Maybe not.

If we're not planning more landing pages, this ticket is not a priority (although the repeated sections on the index page/landing pages is a very small job, one that I probably could have done in the time it took me to write this answer)

**Comment by sjmog** [comment]
Gorram it, we are basically moving towards the modular CSS I initially proposed :imp:

**Comment by spike01** [comment]
Not really, I'd probably favour i18n for the yaml part and it's for a specific part of the site and not everywhere, because the need has emerged. And it's really not a priority for now
