### ISSUE TITLE
Hard to Hire Developers - Landing Page

### ISSUE THREAD

**Issue by isoworg** [makersacademy/website#461]

**Comment by tansaku** [comment]
@isoworg - any chance of a description for this ticket? :-)

**Comment by isoworg** [comment]
I closed this with a PR a while ago - not sure why Waffle didn't do its magic.

@spike01 - have you had a chance to review my PR, with the integration with customer.io ?

**Comment by spike01** [comment]
The PR is fine, but I'm not quite sure what I'm doing on the customer.io side - let's talk about it quickly after (or before?) the standup

**Comment by tansaku** [comment]
thanks @isoworg - can you post a link to the PR and I'll check why it didn't link up - I see three for you on the website repo:

https://github.com/makersacademy/website/pulls?utf8=%E2%9C%93&q=is%3Apr+isoworg

**Comment by spike01** [comment]
It's #462 - we're waiting on the results of tomorrow's meeting with ASTP before proceeding

**Comment by sjmog** [comment]
What's going on with this?
