### ISSUE TITLE
Top menu bar and 'Ask a Question' interferes with content on 13'' screen

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/website#482]
There’s something I still find strange on the website: on the two screenshots, you’ll see it’s almost impossible to read the entire page on a 13’’ laptop. The top menu bar appears/disappears all the time + the ‘Ask a question’ is in the way.

**Comment by rubenkostucki** [comment]
<img width="1280" alt="screen shot 2016-01-03 at 19 44 46" src="https://cloud.githubusercontent.com/assets/2648116/12086334/5e47e250-b2c9-11e5-8be5-4d443ac39440.png">
<img width="1270" alt="screen shot 2016-01-03 at 19 44 57" src="https://cloud.githubusercontent.com/assets/2648116/12086335/5e5dba3a-b2c9-11e5-800a-c3140baa06f2.png">

**Comment by sjmog** [comment]
We can use a media query for vertical heights, although it is painful.

**Comment by nikeshashar** [comment]
@rubenkostucki - it also depends on what size your text is rendered, what size you're keeping the browser etc. 

The Ask a Question button is going to change in the next couple of weeks too.

**Comment by nikeshashar** [comment]
@rubenkostucki closing this as we've moved away from GrooveHQ
