### ISSUE TITLE
Improve youtube partial

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#483]
The current youtube partial is somewhat lacking, namely:

- the overlay doesn't look very good
- it stretches across the scene weirdly
- there are no controls for it

We need to update this as the plan is to start adding graduate videos to augment the testimonials so we'll be relying on a lot more video in the future

**Comment by OlliePorter** [comment]
Here's the attached image of a mockup for a new video carrousel. Arfah and I have been working on it for the 90 second videos, and we're planning on getting it added to the careers page.  

<img width="400" alt="90 second section 2 0 copy" src="https://cloud.githubusercontent.com/assets/13727615/12091841/7d904c06-b2f1-11e5-90e5-22db5a3504b5.png">

**Comment by pitchinvasion** [comment]
The only issue is I'm not sure about having the custom play button, I don't think youtube allows that. Probably the simplest thing is to just use what youtube offers, I'm not quite sure why we don't do that right now

**Comment by sjmog** [comment]
Which page is this to go on @OlliePorter ?

**Comment by pitchinvasion** [comment]
http://www.makersacademy.com/documentary/ is an example of a video that needs fixing. But the idea is to augment the grads slider. Maybe we can sit down the three of us tomorrow?

**Comment by pitchinvasion** [comment]
- [ ] fix documentary video (full screen, alignment, ask a question box hiding it, 90% size with correct alignment using 10% padding on surrounding box??)
- [ ] create new partial using Ollie's design above

**Comment by nikeshashar** [comment]
Could you add the screenshots to the options here please so we can make an informed decision? Thanks

**Comment by pitchinvasion** [comment]
it's the screenshot above nikesh, the question about the overlay is whether we build something like that for every video, or have one generic one. See also the dicussion on the PR linked to this issue, although just to point out we already have Arfah, Ollie, Jordan, me, Dan, and Samm involved in this ticket so I'm wary of getting too many more opinions in

**Comment by nikeshashar** [comment]
@pitchinvasion Happy to discuss my concerns about this when you're in f2f
