### ISSUE TITLE
check github API access capacity

### ISSUE THREAD

**Issue by tansaku** [makersacademy/website#487]
we had some failures:

a 401 Unauthorised error from website/source/employers.html.haml:161:

```- fetch_logos.shuffle```

but only in codeship and not locally, and this is where we are trying to download some JSON over:

https://api.github.com/repos/makersacademy/makers-assets/contents/images/hiring-partners

for some reason the default ACCESS_TOKEN was working locally, but not on codeship, and that token was giving an unauthorised in the browser, so generated a new dev@makersacademy.com token specifically for the website and put that in the codeship config which fixed it (will update lastpass), but am suspicious we may encounter the issue again.

Might be possible to increase limit by adding client secret and client id - which might be a good idea before we get even busier ...

**Comment by danldb** [comment]
Pretty sure this is no longer used. We have a partner_logos_helper.rb but the methods are never called in the new website.  

Anyone know a reason we can't delete this helper?

**Comment by spike01** [comment]
Yup, that's gone since the employers page got a facelift.

🔪 it
