### ISSUE TITLE
Update description of curriculum content on /curriculum

### ISSUE THREAD

**Issue by ptolemybarnes** [makersacademy/website#502]
As an applicant
So that I can evaluate what I'll be learning
I want to get a moderately detailed breakdown of the 12-week course.

At the moment the descriptions of weeks 7 - 9 are not at all representative of what we deliver.

**Comment by pitchinvasion** [comment]
The idea would be to a bit more generic to say things like "full stack javascript week" rather than specifying angular. @jordanpoulton if you can add any ore thoughts we'll look at this next sprint

**Comment by anitacanita** [comment]
After speaking to @jordanpoulton, the idea is for the coachineering team to update it in tech-y terms and then marketing makes it more sales-y.
