### ISSUE TITLE
Update-final-projects

### ISSUE THREAD

**Issue by Arfah** [makersacademy/website#504]

**Comment by ptolemybarnes** [comment]
Is this on the website?

**Comment by ptolemybarnes** [comment]
Do we have a list of the FPs to be added?

**Comment by Arfah** [comment]
Yeap but I'm blocked atm as i'm chasing students for videos etc.

Don't worry about any tickets with my face on them.  They are content related and I do them :-)

**Comment by ptolemybarnes** [comment]
OKie dokey
