### ISSUE TITLE
Add categories to the video yml file

### ISSUE THREAD

**Issue by Arfah** [makersacademy/website#510]
I would like to make campaigns around different videos.

Currently the video partial only links to one set of videos.

I'd like to be able to link to other videos and run landing page campaigns on them.

**Comment by nikeshashar** [comment]
As a marketer
So that I can share multiple types of videos
I would like to be able to create customer video campaigns using the partial

**Comment by nikeshashar** [comment]
I may have found how to do this but need some help with testing it.

**Comment by nikeshashar** [comment]
This applies to the main site and the ronin site.

**Comment by ptolemybarnes** [comment]
- Use same logic used to filter graduate profiles.

**Comment by danldb** [comment]
@Arfah This didn't make it into this weeks sprint. Returning this to backlog for the moment - let me know if you wish to discuss. Feel free to move back into priority before next week's kick off meeting.

**Comment by nikeshashar** [comment]
@Arfah is this still a thing you need?
