### ISSUE TITLE
Make the Employer TypeForm part of the website

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/website#511]
As an employer, 
So that I can show interest in hiring students
I want to fill in a form on the website

Currently, employers have to leave the site to TypeForm and we suspect that this is causing bounces. We are currently aiming to pay attention to our CTR and this is one way we'd like to improve.

**Comment by rubenkostucki** [comment]
Essentially, we would want to reproduce the same logic for onboarding but for Careers so that we can easily change the form, test it and see how it impacts our bounce rate

**Comment by ptolemybarnes** [comment]
Make employer sign up typeform an embedded typeform.
