### ISSUE TITLE
Merge Ronin into MA.com and improve UI

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/website#513]
As a future student (and Hiring Partner),
I want to land on a single page that describes what MA is with a division in pricing and Value Proposition

Onboarding and Careers seem to agree it makes sense to have the whole marketing effort pointing to a single website rather than two different ones

**Comment by nikeshashar** [comment]
@rubenkostucki the reason is missing : So that.....

**Comment by rubenkostucki** [comment]
So that all sales & marketing efforts are targeted on the same website,
whilst allowing our customers to more easily understand the options:

Ronin (£2.5k)
Onsite (£8k)
Private Tuition (£50k) <-- this is something Jordan is keen on

On Wed, Feb 3, 2016 at 5:09 PM Nikesh Ashar <notifications@github.com>
wrote:

> @rubenkostucki <https://github.com/rubenkostucki> the reason is missing :
> So that.....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/website/issues/513#issuecomment-179350962>
> .
>
-- 
Keeping it particularly short as I broke my hand!

___________________________

Ruben Kostucki,
COO

+44 774 829 9962 |  www.makersacademy.com

**Comment by rubenkostucki** [comment]
I kinda liked the pricing table on https://landing.jobs/employers especially if you click on "Compare Plans"

Could be a nice feature: we show Remote vs Onsite with the basic differences (in person, yoga/meditation, coaching team etc.) and there's a 'compare courses' which leads to a more complete comparison table. Having the question mark explaining each also makes sense to me.

I did the mobile check @sjmog @jordanpoulton @Arfah and it looks good to me actually...

**Comment by Arfah** [comment]
Hello. I'm made copy changes where I can. Can @jordanpoulton please look over it...
Main changes are
- About us page
- Added FAQs from Ronin here 
- Added Vlogs to graduate page.. (Even figured out how to make a yaml file for this with @roidriscoll :-D
- Payments page: I removed everything and just kept the table (I think the table is basically everything)

I'm struggling:
- Curriculum Page: I'm really not sure how to add Ronin stuff here.. my suggestion is having a two tab table --- so you select the tab for ronin table too appear or something?  The engineers will need to look into this. 

Other things that need doing...
@pitchinvasion to merge the application once he is back
I need to gather more content like ronin final projects etc but I'll do this on another branch. 

Kthnxbye. 

:-) 
-

**Comment by rubenkostucki** [comment]
Agreed @arfah. On the curriculum page I would also create a comparison table so
people are clear on what's the same and what's different
___________________________


Ruben Kostucki,
COO
@rubenkostucki | +44 774 829 9962 | www.makersacademy.com




On Thu, May 5, 2016 at 4:58 PM Arfah <notifications@github.com> wrote:
Hello. I'm made copy changes where I can. Can @jordanpoulton please look over it...
Main changes are

 * About us page
 * Added FAQs from Ronin here
 * Added Vlogs to graduate page.. (Even figured out how to make a yaml file for
   this with @roidriscoll :-D
 * Payments page: I removed everything and just kept the table (I think the
   table is basically everything)

I'm struggling:

 * Curriculum Page: I'm really not sure how to add Ronin stuff here.. my
   suggestion is having a two tab table --- so you select the tab for ronin
   table too appear or something? The engineers will need to look into this.

Other things that need doing...
@pitchinvasion to merge the application once he is back
I need to gather more content like ronin final projects etc but I'll do this on
another branch.

Kthnxbye.

:-)

**Comment by jordanpoulton** [comment]
First thing to bear in mind @sjmog - EdAid are missing from the list of funding options on the payment's page... Are we up to date with the master branch? @pitchinvasion added EdAid recently.

**Comment by jordanpoulton** [comment]
Just an aesthetic idea, but would it look nice if we added logos to the hero on the landing page?

ONSITE
-INSERT MA'S LOGO AS A WHITE CUTOUT HERE
AT OUR LONDON CAMPUS

REMOTE
-INSERT RONIN LOGO AS A WHITE CUTOUT HERE
FROM THE COMFORT OF YOUR OWN HOME

**Comment by nikeshashar** [comment]
Incorporate #610 to this merge
