### ISSUE TITLE
Gelocalise Employer Page

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/website#518]
As a hiring partner
I want to know that you have developers in my area/city
so that I should bother reaching out to hire your developers

**Comment by pitchinvasion** [comment]
For simplicity let's try just having a query param so you go to https://www.makersacademy.com/employers?City=Manchester and a bit of js will update the title to say "Employers in Manchester" or whatever

**Comment by pitchinvasion** [comment]
http://www.gravitatedesign.com/blog/worried-google-penalties-using-landing-pages/

**Comment by pitchinvasion** [comment]
https://www.quora.com/If-I-make-multiple-landing-pages-for-my-AdWords-adgroups-will-that-negatively-affect-my-SEO

**Comment by pitchinvasion** [comment]
If we do create similar content if we just add a  `noindex` tag it won't be an issue @rubenkostucki

**Comment by rubenkostucki** [comment]
Sounds amazing.
___________________________


Ruben Kostucki,
COO
@rubenkostucki | +44 774 829 9962 | www.makersacademy.com
Looking to Hire Talented Developers? Click here!







On Wed, Feb 10, 2016 at 11:46 AM Leo Allen <notifications@github.com> wrote:
If we do create similar content if we just add a noindex tag it won't be an issue @rubenkostucki

**Comment by pitchinvasion** [comment]
We could search for the nearest major city http://stackoverflow.com/questions/17594401/find-closest-city-to-given-longitude-latitude

**Comment by sjmog** [comment]
So this is a quick JS change @pitchinvasion ?

In the long run I would like student locations to be attached to students in Hub and available through the API. That way we can do numerous cool things, like:

- Give actual numbers of people available to hire in a region
- Build cool graphics that show where people are pair programming, right now
- Other decent geolocated data analysis

But I'm guessing that's well out of scope for this ticket

**Comment by sjmog** [comment]
Also @pitchinvasion if we did a query string, how would they get to the page with the query string? i.e. how would an employer end up on `http://makersacademy.com/employers?location=Manchester`?

**Comment by pitchinvasion** [comment]
through the specific ad that targets them, but this would mean needing to manually set up google campaigns for different areas which will be a pain. The other stuff is different entirely as this is geolocating employers rather than students. 

However I think this ticket should be deprioritised until the landing pages have started getting data as I've no idea at the moment if there's any value in doing this. I've worked with geolocation and it can be more trouble than it's worth

**Comment by sjmog** [comment]
Oh yeeeeah I see

I don't see much benefit to this without being able to actually change content dependent on location. I would suggest deprioritizing this page too

**Comment by rubenkostucki** [comment]
As a hiring partner
So that I can have content targeted for my location
I want the location to change based on the location

This will be based on a utm_campaign tag, we'll need to parse this in JavaScript and dynamically update the page with relevant content

**Comment by pitchinvasion** [comment]
For the city we will have:

utm_campaign name:

CareersManchester
CareersBirmingham
CareeersBristol
