### ISSUE TITLE
New hiring page

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#522]
As a team
So that we can attract great people who are a good fit for the company and our culture
I want a proper hiring page that reflects the self-managed culture at Makers

We need to be more like buffer in this way who get 1000s of people applying every month to work for them:

https://buffer.com/journey

Check an example job ad with slideshow

https://buffer.com/journey/front-end-developer

This is especially important as we look to hire a senior developer

**Comment by rubenkostucki** [comment]
https://www.airbnb.co.uk/careers/departments/position/11422
