### ISSUE TITLE
acast-landing

### ISSUE THREAD

**Issue by Arfah** [makersacademy/website#528]

**Comment by danldb** [comment]
What is this for?

**Comment by Arfah** [comment]
Podcasts

**Comment by ptolemybarnes** [comment]
@Arfah Any more details? The pull request looks fine to me but it's a bit obscure.

**Comment by Arfah** [comment]
it's a landing page as I needed to create a specific page that was linked
to podcast advertising.

On Thu, Feb 11, 2016 at 3:54 PM, Ptolemy <notifications@github.com> wrote:

> @Arfah <https://github.com/Arfah> Any more details? The pull request
> looks fine to me but it's a bit obscure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/website/issues/528#issuecomment-182929815>
> .
>



-- 
Arfah Farooq
<http://t.sidekickopen38.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjvP2W64Jb8q4Y9g2PW5vMrTT56dFrPf3gdQKj02?t=http%3A%2F%2Fwww.arfahfarooq.com%2F&si=5605859451731968&pi=65131f70-afe7-47ce-acab-0300832b3a76>
Say hello on Twitter: @Arf_22
<http://t.sidekickopen38.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjvP2W64Jb8q4Y9g2PW5vMrTT56dFrPf3gdQKj02?t=http%3A%2F%2Fwww.twitter.com%2Farf_22&si=5605859451731968&pi=65131f70-afe7-47ce-acab-0300832b3a76>
 and Linkedin
<http://t.sidekickopen38.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs3LjvP2W64Jb8q4Y9g2PW5vMrTT56dFrPf3gdQKj02?t=http%3A%2F%2Fuk.linkedin.com%2Fpub%2Farfah-farooq%2F44%2F600%2F602%2F&si=5605859451731968&pi=65131f70-afe7-47ce-acab-0300832b3a76>
