### ISSUE TITLE
Improve Employer Form Page

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/website#572]
As an employer,
I'd like to see a nicer sign up page which reminds me on the left what to expect and what MA expects from me
So that I only send an application if it's worth it

**Comment by rubenkostucki** [comment]
I used the Hired.com employer contact page and changed it a little for our need. This is essentially what I'd like it to look like branded MA of course:

Column on the left with some contnet
Column on the right with the form

![screen shot 2016-03-09 at 20 23 27](https://cloud.githubusercontent.com/assets/2648116/13649308/f7f94440-e634-11e5-9505-d095709d3740.png)

**Comment by nikeshashar** [comment]
@rubenkostucki do you still need this?

**Comment by rubenkostucki** [comment]
Nope
___________________________
Ruben Kostucki, COO@rubenkostucki | +44 774 829 9962 |  www.makersacademy.com

"If Brexit is happening, we seriously need to invest in our local talent"







On Wed, Sep 28, 2016 12:29 PM, Nikesh Ashar notifications@github.com
wrote:
@rubenkostucki  do you still need this?
