### ISSUE TITLE
NPS Measurement

### ISSUE THREAD

**Issue by rubenkostucki** [makersacademy/website#573]
As MA,
We re not measuring NPS score, at all, nor effectively
So that we know whether people would recommend MA to others

The solution:
- We automatically send an NPS typeform to all students who have **graduated** (e.g. moved in PD to the jobhunter pipeline) 3 - 6 - 12 months post graduation

**Comment by spike01** [comment]
If this is becoming blocked due to not being an "urgent need", we can look at an integration with https://www.promoter.io/ - it can trigger off segment.

**Comment by spike01** [comment]
Also, we should think about bringing back the weekly NPS surveys. By the by

**Comment by rubenkostucki** [comment]
Not sure that makes sense actually. Promoting (or not) whilst on the course is
totally bias. I think measuring NPS can only happen a few months after
graduation when they can look back and assess whether the training was worth it.
They might give a 0 NPS in week 5 (e.g. battleweb when we had it) but that's
irrelevant. If battwelweb is horrible and painful, but they get a job and it was
useful at the end of it, that's what matters most IMO.
As for promoter.io, can it trigger off when a students has finished the course?
If so, let's totally do it!
___________________________


Ruben Kostucki,
COO
@rubenkostucki | +44 774 829 9962 | www.makersacademy.com
Looking to Hire Talented Developers? Click here!







On Wed, Mar 9, 2016 at 9:08 PM Spike <notifications@github.com> wrote:
Also, we should think about bringing back the weekly NPS surveys. By the by

**Comment by nikeshashar** [comment]
@rubenkostucki let's chat about this. I spoke to Mikhail about getting Chattermill to do all feedback and give us an NPS score for all of onboarding and the students on the course. Let's integrate careers in there too and go all out on my feedback project

**Comment by rubenkostucki** [comment]
OK. The problem isn't the tool and tracking btw, the problem at the moment
is timing the request for it to come out 3-6-9 months after they graduate.
Happy to chat about it :)
On Tue, 15 Mar 2016 at 15:28, Nikesh Ashar <notifications@github.com> wrote:

> @rubenkostucki <https://github.com/rubenkostucki> let's chat about this.
> I spoke to Mikhail about getting Chattermill to do all feedback and give us
> an NPS score for all of onboarding and the students on the course. Let's
> integrate careers in there too and go all out on my feedback project
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/makersacademy/website/issues/573#issuecomment-196877715
>
-- 
___________________________

Ruben Kostucki,
COO

+44 774 829 9962 |  www.makersacademy.com

**Comment by nikeshashar** [comment]
Yeah we can do that - it's what I'm setting up today with some deposit emails etc

**Comment by nikeshashar** [comment]
This is now in place with Delighted / Customer.io

**Comment by nikeshashar** [comment]
Opening new ticket in applications for automation
