### ISSUE TITLE
Press Page on Website

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#590]

**Comment by rubenkostucki** [comment]
http://studenttimes.org/article/news/graduate-news/500th-student-passes-through-makers-academy-bootcamp-doors#.VwuZjxIrKRs

http://uk.businessinsider.com/makers-academy-rings-a-gong-every-time-one-of-its-students-gets-a-job-2016-4

https://www.theguardian.com/technology/2013/oct/14/learn-how-to-code

https://www.theguardian.com/technology/2013/aug/18/wasted-talent-female-tech-women

http://www.independent.co.uk/student/career-planning/getting-job/its-5am-but-im-still-up-and-working-8949645.html?utm_content=bufferf7dc0&utm_source=buffer&utm_medium=twitter&utm_campaign=Buffer

http://www.forbes.com/sites/rogertrapp/2014/01/31/technology-needs-new-role-models/#51e16a00347a

http://www.forbes.com/sites/rogertrapp/2015/09/21/how-business-leaders-can-help-end-the-skills-shortage/#348110ed7a8f

http://techcrunch.com/2014/11/25/tech-city-fellowship/

http://www.theguardian.com/news/2015/dec/03/should-kids-learn-code

**Comment by rubenkostucki** [comment]
There are many more... but it's a start :)

**Comment by nikeshashar** [comment]
@rubenkostucki - Word from @spike01 is that we killed the last press page due to low traffic. Is there a specific campaign based around this?

**Comment by rubenkostucki** [comment]
We might just want a partial on the about us page with a few logos of top
newspapers!? So people who are more interested about us, including joining,
can read about us in the press!?

Not an essential piece. Merging remote and makers + moving to medium is
higher priority in my mind
On Mon, 18 Apr 2016 at 22:43, Nikesh Ashar <notifications@github.com> wrote:

> @rubenkostucki <https://github.com/rubenkostucki> - Word from @spike01
> <https://github.com/spike01> is that we killed the last press page due to
> low traffic. Is there a specific campaign based around this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/makersacademy/website/issues/590#issuecomment-211568038>
>
-- 
___________________________

Ruben Kostucki,
COO

+44 774 829 9962 |  www.makersacademy.com

**Comment by nikeshashar** [comment]
Okay - I'm shelving this for now and then will come back to it once the site is merged

**Comment by nikeshashar** [comment]
Reopened to start wireframing for some press coverage to be displayed site. Diagramming first and then pairing to create some wonderful display of all the press coverage we've had.

**Comment by rachelcdavies** [comment]
AlexB is trialling some 3rd party software to embed in our website.

**Comment by alexandergimson** [comment]
http://www.makersacademy.com/press/

**Comment by nikeshashar** [comment]
This is done now - closing the ticket.
