### ISSUE TITLE
Add link to price change blogpost

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#593]
Need to have the link visible in the 'Apply' partial

AND

Need to link to the blog post from the 'course costs' part of http://www.makersacademy.com/payment/

![image](https://cloud.githubusercontent.com/assets/208986/14607299/eb146ee0-0578-11e6-9cad-ebd429f4c4d5.png)

**Comment by pitchinvasion** [comment]
@jordanpoulton What blog post is that? What is the motivation for doing this?

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/14619617/315fac98-05b0-11e6-8846-0bd7bb36f5ab.png)

**Comment by nikeshashar** [comment]
@jordanpoulton @sjmog @pitchinvasion - something like the above ?? ^^

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/14619682/76405ede-05b0-11e6-8d40-051c4855212c.png)

**Comment by nikeshashar** [comment]
Slightly different wording.

**Comment by jordanpoulton** [comment]
Fine with this - please ensure that it's a live link to the blog post - http://blog.makersacademy.com/changingourprices/
