### ISSUE TITLE
Add "EdAid" to Future Finance and PCDL on Payments page

### ISSUE THREAD

**Issue by pitchinvasion** [makersacademy/website#594]
Post from Jordan:

I have the link to their page, their logo... Just need someone to upload it to the list of funding options at: http://www.makersacademy.com/payment/

Ask me for the logo, and here is the page to link to - https://www.edaid.com/university/makers-academy/apply

**Comment by pitchinvasion** [comment]
Is the logo the one on #593 ?

**Comment by jordanpoulton** [comment]
@leo - Yes, that's the one! Let me know when this is ready to push?

**Comment by leo** [comment]
@jordanpoulton Wrong username 😛

**Comment by jordanpoulton** [comment]
@pitchinvasion ?! ^

**Comment by pitchinvasion** [comment]
haha I'll try and find time tomorrow
