### ISSUE TITLE
Email partial looks funny on landing pages

### ISSUE THREAD

**Issue by Arfah** [makersacademy/website#619]
Hello,

Since the merge the email partial looks funny on the landing pages..

can you sort and make transparent?

See image attached:

![screen shot 2016-06-03 at 14 36 20](https://cloud.githubusercontent.com/assets/8873502/15780281/de99510a-2998-11e6-8c5f-bf4e31fd14d5.png)

**Comment by sjmog** [comment]
@Arfah if you still want to use the email partial we should create another one that can be embedded in heroes like this (but in the design meeting we agreed it was lower-priority than other things we present customers with?)

**Comment by Arfah** [comment]
@sjmog Nope for landing pages its a priority because they enter different email funnels and get given different content depending on what landing page it is.

So yes need a partial like the original hero one.
