### ISSUE TITLE
Create subdomain for remote.makersacademy.com

### ISSUE THREAD

**Issue by jordanpoulton** [makersacademy/website#621]
For now, just have it redirect to www.makersacademy.com, but it will be helpful to have it for marketing.

**Comment by nikeshashar** [comment]
where do you want remote.makersacademy.com to go to? Wouldn't that split the site up again?

**Comment by nikeshashar** [comment]
@jordanpoulton do you still need this?

**Comment by nikeshashar** [comment]
Let's move whatever is at www.makersacademy.com/remote to remote.makersacademy.com.

However much research shows that having a subdomain is worse than having a subfolder on the site. 

We need more Remote content for sure

**Comment by sjmog** [comment]
@jordanpoulton I have set up a new skeleton for making new websites. Go to http://github.com/makersacademy/skeleton to have a look and feel free to make issues there!
