### ISSUE TITLE
Employers form takes negative numbers

### ISSUE THREAD

**Issue by tigretoncio** [makersacademy/website#658]
In the form available at:
http://www.makersacademy.com/employers/contact/
a negative number can be entered into the form field "How many junior developer positions do you need to fill?"

Should not allow to take negative numbers.

Field "How many people do you have on the tech team now?" accepts negative numbers directly typed, but does not accept them using the field arrows appearing when editing the field, so probably the same behaviour should be replicated for the junior dev field.

**Comment by nikeshashar** [comment]
@sjmog @rubenkostucki will this be moved to employers.makersacademy.com? Can I close this ticket?

**Comment by sjmog** [comment]
Closing now.
