### ISSUE TITLE
Team page to be updated

### ISSUE THREAD

**Issue by ChiefJoyOfficer** [makersacademy/website#675]

**Comment by nikeshashar** [comment]
- [ ] Zara
- [ ] Emily
- [ ] Ross
- [ ] Alex
- [ ] Mary
- [ ] Ben

**Comment by nikeshashar** [comment]
As Careers Coach Zara supports our students from the final weeks of the course until they get their first job through group workshops, 121s and developing bespoke resources. Her speciality is working with people in transition having previously worked with young professionals (New Entrepreneurs Foundation) and then supporting women with criminal convictions back into work (Working Chance). On the side she sells pottery in aid of Camphill charity for adults with special needs, is working her way through Gauntlet PS4 and is training to be a psychotherapist.

**Comment by nikeshashar** [comment]
Mary loves helping people learn, and has spent the last few years coaching programmers.  She also loves making things.  She has released two video games, an implementation of Git in JavaScript, and a programming language designed for beginners.

**Comment by nikeshashar** [comment]
Ollie has never been one to follow convention, so he left school at 17 to become an entrepreneur. He’s previously worked in Apple Retail and in the growth department of a tech startup called Gett. Passionate about technology and education, Ollie’s an alumnus of the highly selective entrepreneurs course the New Entrepreneurs Foundation and Gatekeeper here at Makers Academy. Ollie spends his time selecting the very best students for every cohort.

**Comment by nikeshashar** [comment]
Remove "Junior" from Ollie's description

**Comment by EmiKnu** [comment]
Emily is on our careers team, tracking down employers who meet our high standards and helping them to hire the developers we train. She’s new to tech - before Makers Academy, she worked in the charity sector, supporting women with criminal convictions into employment. Her main hobby is going to restaurants by herself, so she can concentrate on the food without any distractions.

**Comment by nikeshashar** [comment]
Ross 
Relationship Manager

Ross came to Makers Academy with a varied past. Never having been a fan of traditional education or the typical sales approach he fell in love with Makers Academy from the beginning. Now he is managing relationships with our hiring partners being driven by his love of people and what motivates them, as well as knowing that the company he represents stands for a change in education.

**Comment by maxbaczynski** [comment]
Max is passionate about improving diversity in tech. Before Makers Academy he spent two years at Apps for Good, inspiring young people from all walks of life to build their digital skills. He is excited to work with hiring partners to improve their hiring processes and attract the best software talent from any background.

**Comment by nikeshashar** [comment]
Added a blocked label as images need to be resized by either @Arfah or @sjmog to match the current styles on our site

**Comment by danldb** [comment]
Is this still blocked? I can't see a PR?
