### ISSUE TITLE
Edit the "Onsite or Remote" section

### ISSUE THREAD

**Issue by roidriscoll** [makersacademy/website#678]
Further to a conversation with Roi, Ross, Jordan, Nikesh and Alex the decision was made to remove the text "Some Streamed (Speaker-Dependent)" and indicate that "Talks by Industry Leaders" are onsite only. 

This removes the need for us to implement professional-standard broadcast streaming facilities.

**Comment by roidriscoll** [comment]
Further to a conversation with Roi, Ross, Jordan, Nikesh and Alex the decision was made to remove the text "Some Streamed (Speaker-Dependent)" and indicate that "Talks by Industry Leaders" are onsite only. 

This removes the need for us to implement professional-standard broadcast streaming facilities.

**Comment by nikeshashar** [comment]
@roidriscoll do we need to specify this for careers talks too?

**Comment by nikeshashar** [comment]
@roidriscoll @jordanpoulton any ideas for wording? I could just replace it with an X?

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/18362876/89a09c04-75ff-11e6-9399-1d9cfc09ee38.png)

**Comment by jordanpoulton** [comment]
Fine by me :)

**Comment by roidriscoll** [comment]
bon :squirrel:
