### ISSUE TITLE
Make estimated pre course time commitments consistent

### ISSUE THREAD

**Issue by maryrosecook** [makersacademy/website#684]
On the [About Us](http://www.makersacademy.com/about-us/) page, it says that the pre course requires 15-20 hours a week.  On the [curriculum](http://www.makersacademy.com/curriculum/) page it says it requires a minimum of 20 hours a week.  On the [pre course introduction](https://github.com/makersacademy/pre_course/blob/master/introduction.md) page, it says it requires 20-30 hours a week.  Could this be standardised to 20-30 hours a week?

**Comment by nikeshashar** [comment]
PreCourse intro updated : https://github.com/makersacademy/pre_course/pull/643
