### ISSUE TITLE
Update Terms 

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#711]
- [ ] Refactor pricing
- [ ] Define terms 
- [ ] Womens discount

**Comment by sjmog** [comment]
@nikeshashar did you get round to this yet?

**Comment by nikeshashar** [comment]
In progress.

**Comment by rachelcdavies** [comment]
@nikeshashar seems to have been in progress for a long time. Will close on the assumption that you can re-open if it still needs doing.
