### ISSUE TITLE
Refactoring Case Studies

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#714]
- [x] Sergio
- [x] Maria
- [x] Marion
- [x] Hannah Carney
- [ ] Mara
- [x] Elia
- [ ] Sivan
- [ ] Richard W
- [ ] Wayne R
- [x] Elia B
- [ ] Van Le
- [ ] Mic 
- [ ] Daniel Ortiz
- [ ] Noah Pollock

**Comment by nikeshashar** [comment]
@Arfah - reminder to get Hannah's pic sorted. Then we can schedule two more for you today / tomorrow

**Comment by sjmog** [comment]
@nikeshashar can we close this?

**Comment by rachelcdavies** [comment]
@nikeshashar I'm going to close this for now.
