### ISSUE TITLE
Incorrect picture used for Maria Romero in Graduate section

### ISSUE THREAD

**Issue by nomi811** [makersacademy/website#730]
The Remote July 2016 picture was used for Maria Romero in the Graduate section for her picture.  She graduated in July, I think, so she was probably in the Remote May 2016 cohort.

**Comment by nikeshashar** [comment]
@Arfah I think we should take this profile off if we don't have the right image in time?

**Comment by rachelcdavies** [comment]
@nikeshashar Closing for now.
