### ISSUE TITLE
Small Improvements from Jordan

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#734]

**Comment by jordanpoulton** [comment]
Mark’s UX CHANGES - from Makers Heuristic Evaluation.key

[ ] Make MA&LOGO in hero a clickable link

[ ] Make REMOTE&LOGO in hero a clickable link

[ ] Find a way to show where we are - make ‘campus’ or similar a link to Google?

[ ] Clarify the audience for the ‘partners’/‘employers’ page

[ ] !=, == and && in the manifesto - confusing?

[ ] Clarity in comparison table

[ ] make ‘pairing’ a link to blog post about pairing?

[ ] Remove asterisk on 4k price point

[ ] ‘Your own practise, at home’ - ‘up to you’ or similar

[ ] ‘In Major Tech Hubs Only’ - clarify what this means

[ ] Add visual detailing application process to apply form

[ ] Clarify on application that date you apply for is flexible

[ ] Remove minimum word count on application?

[ ] Clarify head of comparison table: Onsite & Remote

[ ] Change ‘Learn Ruby in 15’ to ‘Get started in Ruby’ or something?

[ ] Answer more Quora questions

[ ] Raise priority of the ‘reviews’ section in the footer?

[ ] Reorder priorities in ‘payments’ page so providers are top?

[ ] Can we create a jobs guarantee?

[ ] Is ‘600’ seen to be low? We think it’s high, does the viewer?

[ ] People still think Remote is vids, part time, alone...

[ ] Should we offer a women’s discount for Remote?

[ ] Can we make the hero background image a live feed of the office?

[ ] Should there be a separate page going into detail on the application process?

[ ] Autoscroll the grad images?

[ ] Improve TOV in application process

[ ] Justify ‘Europe’s #1 Bootcamp"

[ ] Improve link to blog

[ ] Weave links to blog into the text

**Comment by rachelcdavies** [comment]
Some of these are no longer relevant as we removed remote. Might need to break copy changes out from engineering changes.
