### ISSUE TITLE
Landing page for Diversity (Careers)

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#741]
As a potential Hiring Partner
So that I can see MA's awesome diversity
I would like a landing page that demos this

**Comment by alexkatebailey** [comment]
- [ ] Please can you add the graduates partial under the last section we added, and tag only women to show up.
- [ ] Under that, add the 300+ Companies with CTA section from the employers page.
- [ ] Please also add tracking to form completions clicked through from this page.
- [ ] Please replace email capture in the top banner with a button that says "Let's talk" also linking to the Careers Form (tracking also required.)
- [ ] Set up forwarding from makersacademy.com/employers/diversity to makersacademy.com/diversity

Thanks!!!!

**Comment by rubenkostucki** [comment]
1. " It just so happens that 35% of them are female." sounds weird. Can we rephrase to
"We accept 1 in 10 applicants, and 35% of our developers are women!"

2. "Places for women from disadvantaged backgrounds on our course, through partnerships with IBM and Thoughtworks."

Should be

"Places for women from disadvantaged backgrounds on our course, through partnerships with IBM, Skimlinks and Thoughtworks."

**Comment by rubenkostucki** [comment]
![screen shot 2016-11-22 at 16 05 21](https://cloud.githubusercontent.com/assets/2648116/20531095/926b9f24-b0cd-11e6-969d-ab02d1fb1e3e.png)

looks weird; "We Believe" appears lower than other titles on the same line

**Comment by rubenkostucki** [comment]
![screen shot 2016-11-22 at 16 06 32](https://cloud.githubusercontent.com/assets/2648116/20531122/a87224b4-b0cd-11e6-9509-225e82ce9f5c.png)


The background image is a bit of a waste as it's super nice. I think we should use that one where the TW quote is.

**Comment by rubenkostucki** [comment]
![screen shot 2016-11-22 at 16 08 23](https://cloud.githubusercontent.com/assets/2648116/20531209/e9e8c178-b0cd-11e6-8e1f-83a37275d332.png)


List of logos should be different and include:

FT
BBC
CTM
Deloitte Digital
Sky
Atos
JustGiving

**Comment by rubenkostucki** [comment]
:shipit:
