### ISSUE TITLE
301 Redirect to employers.makersacademy.com

### ISSUE THREAD

**Issue by alexkatebailey** [makersacademy/website#758]
From www.makersacademy.com/employers
And http://www.makersacademy.com/employers/contact/
Are there any employers/ pages floating around that should also be included?

**Comment by nikeshashar** [comment]
Anything in the `/employers` folder + partials will need to move across. And we can then clear them from the website.

**Comment by sjmog** [comment]
I'll pop in a 301 that redirects now.
