### ISSUE TITLE
Add Ebook Landing Page on Employers

### ISSUE THREAD

**Issue by alexkatebailey** [makersacademy/website#786]
So I can learn "5 reasons I'm not getting the tech talent I want." 
So that I can believe Makers Academy can help me with hiring.
I need to download this ebook on a targeted page with no distractions.

**Comment by nikeshashar** [comment]
@alexkatebailey do you want this on the website or the employers site?

**Comment by alexkatebailey** [comment]
employers - sorry. I tried moving it

**Comment by nikeshashar** [comment]
That's okay. We can't move tickets as each one belongs to a specific github repo. I'll close this one.
