### ISSUE TITLE
Update payments page

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#860]
- [ ] Remove bank transfer
- [ ] Add qardhasan

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/24247382/699f2b9c-0fc3-11e7-9c27-08daf7c212c9.png)

Bank transfer removed and text added below each payment option v1

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/24247412/8580da5e-0fc3-11e7-9179-987be52fd4ca.png)

V2

**Comment by jordanpoulton** [comment]
:shipit:

**Comment by nikeshashar** [comment]
Lol. Which one @jordanpoulton

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/24249328/bab4fc30-0fca-11e7-9803-74f243e9d22f.png)

V3 ?

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/24255710/1e3cb460-0fde-11e7-8e8f-75953d8ca059.png)

I think this is better

**Comment by nikeshashar** [comment]
![image](https://cloud.githubusercontent.com/assets/7963753/24289748/7f30ee0c-107a-11e7-8a51-979baf9e3c1c.png)
