### ISSUE TITLE
Interview Form C4 Fields

### ISSUE THREAD

**Issue by OlliePorter** [makersacademy/website#863]
Add a C4 radio box/check box grading and total field to interview form for C4 qualities.

Code: ( ) ( ) ( ) ( ) ( ) 
Competence: ( ) ( ) ( ) ( ) ( ) ( ) ( )
Confidence: ( ) ( ) ( )
Communication: ( ) ( ) ( ) ( ) ( ) 
TOTAL: _ / 20

**Comment by nikeshashar** [comment]
@OlliePorter are you sure you want this on the website?

**Comment by OlliePorter** [comment]
@nikeshashar yes... The interview form? Is this not in the right place?

**Comment by nikeshashar** [comment]
Nope - sorry dude. You want to open this in the applications repo. I'll close this issue for now. github.com/makersacademy/applications

**Comment by OlliePorter** [comment]
@nikeshashar ah OK. Redone for applications ;)
