### ISSUE TITLE
Landing Page for new LR15 book

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#913]
We're launching a new version of our Learn Ruby in 15 minutes ebook. I'd like to make a fun, innovative way for people to get the book. I'd like to have the users land on a page that presents them with a puzzle / quiz and if they are successful in answering said quiz - we can email them a copy of our PDF. Some example quiz questions can be seen at www.makersacademy.com/quiz
Ideally we'd like to collect some sort of social signin or challenge your friends to answer this through Facebook / Twitter etc.

* Code produced should have tests that can be run to check it's working properly & be code reviewed to our usual standards
* You're free to choose the language
* The look / feel should be that of makersacademy.com
* We'll be on hand to answer questions about code / design / UX

**Example userflow :**
Land on page
See & complete puzzle or short quiz (see makersacademy.com/quiz)
Social media share
Collect email address to access to PDF file
Email address sent to customer.io (we'll advise on this)

**Future :**
We may share / create more tutorials this way so people could revisit the site and redownload the tutorial or be emailed about new ones we're making

**Comment by nikeshashar** [comment]
- As we discussed there will be one challenge/question only. Do you want to have a set of basic challenges (just like the example from the interview), and then randomly generate only one, or start with only one challenge/question?
- What should happen if the answer is wrong? The right answer should be visible with some explanation and then show the email input field?
- Now the email-capture is added to the front page. Should the one challenge/question stay there and then show the email-capture if question is answered? Or should we use makersacademy.com/quiz for this purpose?
- As I understand the email_capture.js uses the content of the ‘newsletter_email’ field and submits it to the segment.com. Should this js be updated in order to submit email to customer.io?
- Earlier you mentioned the social share as a requirement. Do you still want to have the social share feature implemented here?

[18:25] 
As I see you use haml. I have no experience with it (when I worked with templates I always used erb in ruby), so I will spend some time today to get the basic understanding of it :slightly_smiling_face:

[18:26] 
but haml seems to be simpler than erb

**Comment by nikeshashar** [comment]
From above : 

* I believe we should start with one question as part of the MVP. Once that works we can then iterate over it and add the functionality in for randomising questions. 

* If the answer is wrong we'd show a text box with a prompt that's pre populated. I can send that across when you need it. 

* The landing page would show the question first and nothing else. Once they question has been correctly answered we can then ask for an email address. 

* `segment.io` will pass the information across to all of our tools, including customer.io

* Social share can be a feature we add later.

**Comment by nikeshashar** [comment]
`rake publish:staging`

**Comment by nikeshashar** [comment]
Question : 

If you enter this series of commands into a computer, what would you expect the output to be. 

a = 10
b = 20
a = b

Answers :

We'd then have two input boxes where we're checking if they answer correctly. 

Wrong Answer  : 

Prompt : Think of this in the same way a computer would. Or even better, try it out in [IRB](http://bit.ly/playingwithcode)

**Comment by nikeshashar** [comment]
From Peter : 

Peter Miklos [11:54] 
I'm thinking about testing the view. I tried to find example in the spec folder about testing the front end js files, but it seems that only the track-form.js and the rb helper files are tested. I did not find any test for the views. But I'm trying to deliver tests for the view now

[11:54] 
any recommendation? :slightly_smiling_face:

**Comment by peter-miklos** [comment]
I'm going to use capybara, let's see how it works with middleman.

**Comment by peter-miklos** [comment]
**Test status:**
Capybara, selenium-webdriver added to the project, and capybara tests work well with middleman. Test cases added but there is an issue with JS rendered content (details below).

**Test Issue:**
According to capybara help, it should wait for the content rendered by js (wait time can even manually changed), and it seems it does wait, but relevant test cases do not find the expected content, just an empty tag in html —> for instance in a div where the js rendered content should be a question, it finds just this: “” (the issue exists only when test runs). In general the front-end javascript just does not work in these tests.
So now it’s pretty hard to test properly, but I will investigate more. I could not find any similar tests in the current website project folder (mostly the helper files are tested), however does any of you have any suggestion how to solve this issue?
