### ISSUE TITLE
Improve navigation to employers

### ISSUE THREAD

**Issue by rachelcdavies** [makersacademy/website#966]
Make it easier to get to Employers site from main website. Discussing UX ideas and then we'll review designs with all impacted teams.

**Comment by roidriscoll** [comment]
@alexkatebailey created this document: https://docs.google.com/presentation/d/1x3FNXUTE1w3realM69k-2RS30aix8qDL5py2AZDuyzo/edit?ts=59678fa9#slide=id.p

**Comment by roidriscoll** [comment]
Discussed further with Alex yesterday, important to bear in mind consistency between the employers.makersacademy.com and the navigation elements on the main site

**Comment by roidriscoll** [comment]
The navigation bar on the main site is at capacity in terms of links, so fitting a link to employers there will be tricky

**Comment by roidriscoll** [comment]
A "split gateway" on the homepage of the site (as seen in slide one of this document: https://docs.google.com/presentation/d/1x3FNXUTE1w3realM69k-2RS30aix8qDL5py2AZDuyzo/edit?ts=59678fa9#slide=id.p) will be a more drastic change, but possibly the most clear in terms of navigation paths for users. It will also make it easier for us to guage impact on traffic.

**Comment by roidriscoll** [comment]
Smaller changes would be to either fit a link to 'Employers' on the main site navigation bar, but this will impact UX once the user clicks through to employers.makersacademy.com  - the other suggestion would be to overhaul http://www.makersacademy.com/career-support to become a more generic careers portal that allows the user to choose to investigate the employers site, or learn about career support as a prospective student (using a navigation device as detailed in the comment above - just not on the homepage)

**Comment by roidriscoll** [comment]
Next step is to come up with some visual mockups

**Comment by roidriscoll** [comment]
![makersemployersux](https://user-images.githubusercontent.com/2243253/28328230-c0fe2fc0-6bdd-11e7-91e9-f8fbe2d9b7be.png)

**Comment by roidriscoll** [comment]
Currently struggling to find a way to make sure employers (or students who venture down the wrong path) can know how to get back to the main site easily. Reducing UX confusion must be a priority.

**Comment by roidriscoll** [comment]
Conversation between @alexkatebailey and myself:

roi 
[5:23 PM] 
Heya, can you take a look at the mockup I put here when you get a min? https://github.com/makersacademy/website/issues/966


alexb [5:27 PM] 
Hey @roi - looks good! Love the copy :wink: Do you think we'd also be able to change the H1?



----- Today July 19th, 2017 -----
roi 
[9:59 AM] 
Yeah the content is up to you lot! I’m just making sure we’re aligned in terms of navigation etc


new messages
alexb [10:05 AM] 
Ok cool! I'll have a think about this today

**Comment by roidriscoll** [comment]
The 'hello' bar has a 33% higher click-rate than the 'learn about hiring...' button below the fold.

**Comment by roidriscoll** [comment]
"ARE YOU HIRING DEVELOPERS?" on http://www.makersacademy.com/career-support/ gets a far higher click-through rate than any other HP-related link on the site. @alexandergimson is curious to see if a more explicit copy change would affect success of the "BECOME A HIRING PARTNER" partial on the homepage

**Comment by roidriscoll** [comment]
"Learn about hiring our developers" not a call to action. Button could be emphasised more effectively. Hiring partner logos are poorly-integrated into the design

**Comment by roidriscoll** [comment]
We could edit/replace Hellobar to be more eye-catching. An A/B test might prove useful in this situation

**Comment by roidriscoll** [comment]
Hellobar interrupts logo on our footer - might be worth putting some padding at the bottom to account for this.

**Comment by roidriscoll** [comment]
@alexandergimson is running an A/B test within Hellobar to see if using the MA red colour for a background increases engagement

**Comment by roidriscoll** [comment]
Change links on MA.com to point to employers.makersacademy.com

**Comment by roidriscoll** [comment]
@alexkatebailey recommends that we replace the logo partial on MA.com with the one from employers.ma...

**Comment by roidriscoll** [comment]
@alexkatebailey was surprised to see the logos are clickable. Do we encourage this? It makes it very difficult to control the UX if we're unclear that certain elements are navigation options

**Comment by nikeshashar** [comment]
@roidriscoll - we've had chats about this before. Quite length when we wanted the MA / Remote logo's clickable on the apply page. @sjmog was quite adamant that this is behaviours that we don't want on the website.

**Comment by rachelcdavies** [comment]
@roidriscoll will break this into smaller stories

**Comment by rachelcdavies** [comment]
Closing this epic as I think we did the work in other tickets and we'll create smaller tickets for remaining changes.
