### ISSUE TITLE
Typo - Code of Conduct

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/website#992]
> We’ll talk with you work out what, if anything, you’d like to do.

Insert "to"

> You must address people by the name they give you when not addressing them by their username or handle

Make this more relevant / clearer 

(this is based on feedback from a legal copywriter that has applied to the course).

**Comment by nikeshashar** [comment]
@maryrosecook @neoeno Would be interesting to hear your thoughts on the 2nd point above. It came as feedback to us. Do you think we could make the sentence read better?

**Comment by maryrosecook** [comment]
* +1 on the "to" typo.
* How about, "You must address people by the name they prefer.  When online, it's fine to address them by their username."

**Comment by nikeshashar** [comment]
Awesome. Thanks @maryrosecook
